# CoreMail — rspamd Aktionsschwellen
# Werte werden über das ECP dynamisch angepasst (via rspamd Controller API)

actions {
  reject = 15;        # Score ab dem E-Mails abgewiesen werden
  add_header = 6;     # Score ab dem X-Spam-* Header gesetzt werden
  greylist = 4;       # Score ab dem Greylisting aktiv wird
}
