apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coremail.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coremail.labels" . | nindent 4 }}
data:
  DOMAIN: {{ .Values.global.domain | quote }}
  REDIS_URL: "redis://{{ include "coremail.fullname" . }}-redis-master:6379"
  MINIO_ENDPOINT: "http://{{ include "coremail.fullname" . }}-minio:9000"
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_BUCKET: "mail-attachments"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ include "coremail.fullname" . }}-otel-collector:4318"
  METRICS_PORT: "9464"
  BACKUP_S3_ENDPOINT: "http://{{ include "coremail.fullname" . }}-minio:9000"
  BACKUP_S3_BUCKET: "coremail-backups"
  BACKUP_S3_REGION: "us-east-1"
  BACKUP_RETENTION_DAYS: "30"
  SMTP_HOSTNAME: {{ .Values.global.domain | quote }}
  EWS_URL: {{ printf "https://%s/EWS/Exchange.asmx" .Values.global.domain | quote }}
  AUTODISCOVER_URL: {{ printf "https://%s/Autodiscover/Autodiscover.xml" .Values.global.domain | quote }}
